### ISSUE TITLE
Web Crawlers

### ISSUE THREAD

**Issue by benclmnt** [benclmnt/til#27]
How to identify?

From [discourse](https://github.com/discourse/discourse/blob/main/config/site_settings.yml)
```
  non_crawler_user_agents:
    hidden: true
    default: "trident|webkit|gecko|chrome|safari|msie|opera|goanna|discourse"
    type: list
    list_type: compact
  crawler_user_agents:
    hidden: true
    default: "rss|bot|spider|crawler|facebook|archive|wayback|ping|monitor|lighthouse"
    type: list
    list_type: compact
 ```

[Verifying Googlebot](https://developers.google.com/search/docs/crawling-indexing/verifying-googlebot)
