### ISSUE TITLE
Running a stateful container using colima

### ISSUE THREAD

**Issue by benclmnt** [benclmnt/til#3]
As of 19 July 2023, there is a limitation if you want to mount a writable folder into a container volume.

As mentioned [here](https://github.com/abiosoft/colima/issues/83#issuecomment-1339269542), you should add the following into your `/Users/<username>/.lima/_config/override.yaml`:

```
mountType: 9p
mounts:
  - location: "/Users/<username>"
    writable: true
    9p:
      securityModel: mapped-xattr
      cache: mmap
  - location: "~"
    writable: true
    9p:
      securityModel: mapped-xattr
      cache: mmap
  - location: /tmp/colima
    writable: true
    9p:
      securityModel: mapped-xattr
      cache: mmap
```

and restart colima: `colima delete && colima start`.
